name: DeePTB tests.

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Activate base environment
      run: |
        source $CONDA/bin/activate
    - name: Update base environment
      run: |
        source $CONDA/bin/activate
        $CONDA/bin/conda update -n base -c defaults conda
    - name: Install DeePTB
      run: |
        source $CONDA/bin/activate
        conda install pip
        conda update pip
        git clone https://github.com/deepmodeling/DeePTB.git
        cd ./DeePTB
        pip install .
        pip install pytest
    - name Run Test
      run: |
        pytest ./dptb/tests/
